name: CI/CD Csv-Ingestion (Vercel Deploy)

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: code checkout
      uses: actions/checkout@v4

    - name: node setup
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install
      run: npm install

    - name: Lint it
      run: npm run lint

    - name: Preview it
      run: npm run preview

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: code checkout
      uses: actions/checkout@v4

    - name: node setup
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install
      run: npm install --prod

    - name: Deploy
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}